spring:
  application:
    name: auctions
  config:
    import: "optional:configserver:http://localhost:18071/"
  jackson:
    time-zone: UTC
#  datasource:
#    url: jdbc:h2:mem:auctiondb;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#  h2:
#    console:
#      enabled: true
  cloud:
    bus:
      enabled: false
    function:
      definition: auctionCompleted;auctionInvalid
    stream:
      bindings:
        auctionStarted-out-0:
          destination: auction-started
          content-type: application/json
        auctionEnded-out-0:
          destination: auction-ended
          content-type: application/json
        auctionDeleted-out-0:
          destination: auction-deleted
          content-type: application/json
        auctionInvalid-in-0:
          destination: auction-invalid
          group: auctions-service
        auctionCompleted-in-0:
          destination: auction-completed
          group: auctions-service
      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  show-spring-cloud-functions: false

